### ISSUE TITLE
PRIMARY KEYs should be TYPE bigint [CASCADE]

### ISSUE THREAD

**Issue by autochthe** [GMOD/Chado#1]
PostgreSQL uses `bigint` to manage SEQUENCEs (the data structure used to maintain the `serial` data type.  This should be paired with a column of type `bigint`, which is denoted by the type name `bigserial` in a CREATE TABLE declaration.  Without this, eventually INSERTs will fail with the message `ERROR: integer out of range` as the serial begins to return ids that are too large for the column type.

__This is a change that would have far reaching implications, affecting all columns that are foreign keys.__

The following are related to this issue:
* ALTER TYPE of feature.seqlen to bigint
* ALTER TYPE of featureloc.fmin, featureloc.fmax to bigint

**Comment by spficklin** [comment]
I think this should be 'bigserial' rather than 'bigint'.

**Comment by scottcain** [comment]
Done--it took a while even with some perl onliners to help.
