### ISSUE TITLE
JAVA version in Travis build must be updated

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#112]
```
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

```

from the error it is clear --feature must specify 9-14, but we specify 8.... but unfortunately, knowing where to fix this in the Travis build is less clear, since i dont think we install java ourselves, but instead rely on `language: generic`?  A quick google suggests we need to specify the `trusty` distribution instead: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/10

noticed in the #92 PR

**Comment by scottcain** [comment]
Updating java doesn't appear to be enough.  I tried updating it for #92 but then it failed to get flyway:
```
A problem occurred configuring root project 'Chado'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.flywaydb:flyway-core:5.2.4.
     Required by:
         project : > org.flywaydb.flyway:org.flywaydb.flyway.gradle.plugin:5.2.4 > gradle.plugin.com.boxfuse.client:gradle-plugin-publishing:5.2.4
      > Could not resolve org.flywaydb:flyway-core:5.2.4.
         > Could not get resource 'https://plugins.gradle.org/m2/org/flywaydb/flyway-core/5.2.4/flyway-core-5.2.4.pom'.
            > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/org/flywaydb/flyway-core/5.2.4/flyway-core-5.2.4.pom?referrer'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by scottcain** [comment]
I don't get it: why does #110 pass but #92 doesn't?

**Comment by jogoodma** [comment]
I've fixed the build.  We have to use openjdk11 for it to work.  Oracle withdrew their "headless" download so travis had to setup redirects to openjdk when it was specified in builds.  OpenJDK9-10 have an issue with SSL certs and while there were a few workarounds it was simpler to move to openjdk11.  This is why older builds worked but more recent ones have failed.  I've seen no issues with the jump from 8 to 11.
