### ISSUE TITLE
Expand analysis table description

### ISSUE THREAD

**Issue by mestato** [GMOD/Chado#113]
Tripal and possibly others have been using the analysis table in a broader way than currently described. We (PAG Codefest 2020) propose the following description update:

Old analysis table description:
“An analysis is a particular type of a computational analysis; it may be a blast of one sequence against another, or an all by all blast, or a different kind of analysis altogether. It is a single unit of computation.”

Suggested new analysis table description:
"An analysis is a particular type of a computational analysis; it may be a blast of one sequence against another, or an all by all blast, or a different kind of analysis altogether. It can be a single unit of computation or an analysis that represents a set of computational steps. For example, a reference genome assembly could be stored as a single record in the analysis table, but this analysis could encompass many individual analysis steps (read trimming, assembly, scaffolding, etc). These could be stored and related via the analysis_relationship table."

**Comment by scottcain** [comment]
Merged
