### ISSUE TITLE
cvterm table

### ISSUE THREAD

**Issue by lmanchon** [GMOD/Chado#132]

**Comment by lmanchon** [comment]
--Hi all,

is it possible to add a new vocabulary term in cvterm table without breaking links or prevent future chado updates ?

thank you --

**Comment by laceysanderson** [comment]
Hi @lmanchon, I'm not sure I understand your question...

The cvterm table in Chado is designed for each entry/row/record in the table to be a new vocabulary term. Entries are added to this table and then referenced throughout the rest of Chado via their cvterm_id and foreign key relationships. 

Chado is a very slow-changing schema that always maintains backwards compatibility so as long as you are not changing the structure of the cvterm table (i.e. removing columns or changing table constraints) then you should not need to worry about any problems with future Chado updates :-)

Was that helpful? If not, feel free to provide more detail about your specific situation (maybe with an example) and I'll try again!

**Comment by lmanchon** [comment]
--Hi Anne,

thank you for your quick answer.
This is an example: as i work with stemcell i need to use some specifics term relative to stemcell, ie: iPS, MSc ...
So how can i do to add those terms in dedicated vocabulary tables , because they don't exist in the current version of chado.

thanks again

**Comment by jogoodma** [comment]
Hi @lmanchon,

Chado is only a schema that defines the SQL structure and where terms go, it does not have any terms that come as a part of it. It is the task of whoever is working with or populating the schema to load terms that are required. Having said that, there are some ontologies that are almost always used with Chado (e.g. Sequence Ontology; SO). If you need specific stemcell terms then what I would suggest is that you identify an ontology ([Cell Ontology?](https://obofoundry.org/ontology/cl.html)) that has the terms you require and load that into your Chado instance. There are a few options for loading ontologies into Chado, so depending on which one you select we can help you through that process if need be. What we can't do is add a stem cell term to Chado for your use case.

**Comment by lmanchon** [comment]
ok i understand.
I have found my ontology i need: https://www.ontobee.org/ontology/OSCI
but there isn't obo file and Ontology Loader module from chado need an obo file.  Do you have a clue to import the OSCI ontology into Chado ? Thank you --

**Comment by jogoodma** [comment]
I'm not aware of any OWL -> Chado loaders, but it is also not something that I follow closely. @laceysanderson does Tripal have any OWL loaders?

Outside of using an OWL -> Chado loader I think you are left with doing a lossy conversion of OWL -> OBO and then using a Chado OBO loader or looking for an OWL parsing library and writing your own Chado loader with that.

**Comment by laceysanderson** [comment]
Unfortunately, I don't know of any Chado OWL loaders either. So that leaves you with @jogoodma suggestion of converting your OWL file to OBO format or writing your own parser/loader...

**Comment by lmanchon** [comment]
nowadays all ontologies are available in owl format, so I don't see how tripal can import this format?
There is no owl to obo converter. Robot and owltools don't work because owl files have redundancies and can't be converted to obo.

**Comment by spficklin** [comment]
We really do need an OWL importer for Tripal. We started one a few years ago but lost the person working on it and it hasn't resurrected.
