### ISSUE TITLE
Chado / Drupal compatibility

### ISSUE THREAD

**Issue by lmanchon** [GMOD/Chado#133]
--Hi all,

i want to know which version of drupal and chado to choose to avoid problem of compatibility.
I have tested Drupal 9.3.7 and 9.3.15 with Chado and it's not compatible.

thank you --

**Comment by spficklin** [comment]
Hi @lmanchon .   Chado on its own is not compatible at all with Drupal.  Tripal is a suite of Drupal extension modules that provides an interface to integrate Chado and Drupal. The stable release of Tripal is for Drupal 7.  Currently, the Tripal developers are actively working to support Drupal 9.  Unfortunately, when Drupal switched from 7 to 8 (and then 9) they reworked a lot of the interface so it is taking time to rewrite Tripal to support Drupal 9.  We're making progress.  If you'd like to follow along you can get connected via any of the methods listed on our community page:  https://tripal.info/community.  Hope this helps answer your question.
