### ISSUE TITLE
problem to load drush_print function

### ISSUE THREAD

**Issue by lmanchon** [GMOD/Chado#134]
--Hi,

Tripal can't prepare Drupal and Chado and failed with:

Error: Call to undefined function drush_print() in tripal_chado_prepare_chado() (line 214 of /var/www/drupal/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc).

i don't know why function drush_print() can't be loaded.
thank you --

**Comment by spficklin** [comment]
HI @lmanchon .  This issue is caused from using Tripal and not related to Chado itself.    But, I can help with the Tripal side of things.   Do you have Drush installed?

**Comment by scottcain** [comment]
@lmanchon Did you sort this out over at Tripal?

**Comment by laceysanderson** [comment]
Closing this out as it is Tripal specific and quite old at this point.
