### ISSUE TITLE
Add uncertainty values for geographic coordinates in nd_geolocation

### ISSUE THREAD

**Issue by dsenalik** [GMOD/Chado#136]
The geographic coordinates (latitude, longitude, altitude) store in the ```nd_geolocation``` table may not always be precise values.
Issue #135 made me think to propose an addition to this table, additional columns to store the uncertainty value. Older data may not have the precision we can get today with GPS, or in some cases the location is just a country name. Having uncertainty values could allow having coordinates and express the actual uncertainty in the precise location.
This information could be stored as a property, but I feel that the uncertainty is a fundamental property of these values and should be stored alongside them.

I have implemented these additional columns at carrotomics.org, and an example presentation at https://www.carrotomics.org/bio_data/66560 is
![deviation](https://user-images.githubusercontent.com/8419404/201167019-11febbc6-1ccd-4817-8697-360874dea41b.png)

I am curious what others think about this idea.

```
                                                 Table "chado.nd_geolocation"
      Column       |         Type          | Collation | Nullable |                          Default                          
-------------------+-----------------------+-----------+----------+-----------------------------------------------------------
 nd_geolocation_id | bigint                |           | not null | nextval('nd_geolocation_nd_geolocation_id_seq'::regclass)
 description       | text                  |           |          | 
 latitude          | real                  |           |          | 
 longitude         | real                  |           |          | 
 geodetic_datum    | character varying(32) |           |          | 
 altitude          | real                  |           |          | 
 latitude_dev      | real                  |           |          | 
 longitude_dev     | real                  |           |          | 
 altitude_dev      | real                  |           |          | 
Indexes:
    "nd_geolocation_pkey" PRIMARY KEY, btree (nd_geolocation_id)
    "nd_geolocation_idx1" btree (latitude)
    "nd_geolocation_idx2" btree (longitude)
    "nd_geolocation_idx3" btree (altitude)
Referenced by:
    TABLE "nd_experiment" CONSTRAINT "nd_experiment_nd_geolocation_id_fkey" FOREIGN KEY (nd_geolocation_id) REFERENCES nd_geolocation(nd_geolocation_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
    TABLE "nd_geolocationprop" CONSTRAINT "nd_geolocationprop_nd_geolocation_id_fkey" FOREIGN KEY (nd_geolocation_id) REFERENCES nd_geolocation(nd_geolocation_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
```

**Comment by scottcain** [comment]
It seems like storing this sort of information (if you have it) is a pretty good idea. The alternative would be to store this information in nd_geolocationprop. Are there pros/cons? Of course, but since I don't use this kind of data, I can't speak to them. Anybody else?

**Comment by dsenalik** [comment]
The con is we are changing a chado table! But because we are only adding to it, not changing existing columns or anything, any older code will be unaffected.
For me the pro is that the number and its uncertainty logically go together. As you said, it could always be stored as a property too. I just want to know what others think.

**Comment by spficklin** [comment]
@dsenalik what kinds of information are you storing in that uncertainty column? I mean, can you give some examples?

**Comment by dsenalik** [comment]
For some GRIN accessions, location are in degrees, minutes seconds, but only the latitude degree, or only degree and minute are available, seconds missing. so uncertainty would be plus or minus one half degree in the first case (0.5), one half minute in the second (1/60/2=0.0083 = 1/2 minute).

**Comment by dsenalik** [comment]
```
/**
 * Add three new custom columns to chado.nd_geolocation table
 * to store uncertainty (plus or minus) values
 */
function carrotomics_update_nd_geolocation() {
  db_add_field('chado.nd_geolocation', 'latitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of latitude',
  ]);
  db_add_field('chado.nd_geolocation', 'longitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of longitude',
  ]);
  db_add_field('chado.nd_geolocation', 'altitude_dev', [
    'type' => 'float',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Half of the width of the range of uncertainty of altitude',
  ]);
}
```

**Comment by dsenalik** [comment]
I feel like I'm the only one that wants this lol. So that, and the fact that these should probably be properties since a cv term should probably be associated to define exactly what the definition of the uncertainty is, I am going to close this.
