### ISSUE TITLE
gmod_load_cvterms.pl does not load synonym types

### ISSUE THREAD

**Issue by bellerbrock** [GMOD/Chado#23]
The current loading script does not populate the type_id column:
```
foreach my $s ($novel_terms{$k}->get_synonyms() ) {
		    $s=~ s/\s+$//;
		    $s =~ s/\\//g;
		    message("...adding synonym  '$s'  to the database...\n");
		    $new_term->add_synonym($s);  #need to add a type_id to each synonym!
}
```
A change to something like `$new_term->add_synonym($s, { type => 'exact' , autocreate => 1} );` could do the trick, but how to identify the correct types? EXACT, NARROW, BROAD, and RELATED seem standard in .obo files, but there may also be a need for loading custom types.

**Comment by bellerbrock** [comment]
Ok, I don't have permission to create and push a branch, but this is a potential fix working in my local repo: 
```
foreach my $s ($novel_terms{$k}->get_synonyms() ) {
$s =~ s/\\//g;
my ($name, $type) = ($s =~ /^"([^"]+)"([^"[]+)/);  # to parse obo lines e.g, 'synonym: "Ion" EXACT [ChEBI:]'
$type=~ s/\s+//g;
message("...adding $s synonym name '$name'  to the database with type $type...\n");
$new_term->add_synonym($name, { synonym_type => $type , autocreate => 1});
}
```

**Comment by bellerbrock** [comment]
Here's an improved fix that tracks and skips duplicate synonyms:
```
my %loaded_synonyms = ();
foreach my $s ($novel_terms{$k}->get_synonyms() ) {
	$s =~ s/\\//g;
        my ($name, $type) = ($s =~ /^"([^"]+)"\s([^"[]+)/);
        $type=~ s/\s+$//;
        if (!$name || $loaded_synonyms{$name}) { next; } #skip duplicate synonyms
	message("...adding $s synonym name '$name'  to the database with type $type...\n");
	$new_term->add_synonym($name, { synonym_type => $type , autocreate => 1});  #adds synonym with type
        $loaded_synonyms{$name} = 1;
}
```

**Comment by nmenda** [comment]
@bellerbrock I can commit this change, do you want to make the synonym_type all lower case or all upper case? The unique constraint in case sensitive, so would be better to standardize this to avoid duplicates ("Exact" "EXACT" "exact" etc. )

**Comment by bellerbrock** [comment]
@nmenda 
Good idea. I don't have a strong preference, but I'd lean towards uppercase. That's what I've seen so far in CHEBI, and some of the types included acronyms where uppercase makes the most sense.
```
 RELATED FORMULA
 EXACT
 RELATED
 EXACT IUPAC_NAME
 RELATED SMILES
 RELATED InChI
 RELATED InChIKey
 RELATED MASS
 RELATED MONOISOTOPIC_MASS
```

**Comment by nmenda** [comment]
I checked other ontologies, and the type is upper case. I'll just leave it as is now so it does not mess up the CHEBI camel case synonym types

**Comment by spficklin** [comment]
What vocabulary are you adding those terms to?  The Tripal OBO loader handles this by creating a 'synonym_type' vocabulary and putting them there.  Would that work for default Chado as well?

**Comment by nmenda** [comment]
yes, the cvtermsynonym table has a type_id with cv.name 'synonym_type' 
https://github.com/solgenomics/bio-chado-schema/blob/master/lib/Bio/Chado/Schema/Result/Cv/Cvterm.pm#L1882

**Comment by nmenda** [comment]
@bellerbrock what format do you have in the obo file for CheBI? 
Is it always in this format:

`synonym: "some synonym name" RELATED []`

**Comment by bellerbrock** [comment]
Hi Naama,

The CHEBI obo file is in the sgn/cassbase repo if you want to look at it.
But yes, all the synonyms should be in that format.

**Comment by nmenda** [comment]
@bellerbrock you can pull the changes I made 
https://github.com/GMOD/Chado/commit/16a7bdfbb739a0d307566d158cc3af0ce5fbb49a

You will also need to update Bio::Chado::Schema (the copy from the solgenomics project) , there was an error in the delete_synonym function

https://github.com/solgenomics/bio-chado-schema/commit/a268fe08f356084389aa921b3be23443ef5b3467

If it works with your CHEBI subset you can close the issue
