### ISSUE TITLE
Add cvalue_id to all prop tables

### ISSUE THREAD

**Issue by scottcain** [GMOD/Chado#26]
Adding a cvalue_id field to the biomaterialprop table, as is done for the natural diversity module. This allows the property values to also utilize a cvterm.  The idea is to produce something similar to what was done with several natural diversity modules where values could be either be free text or from a controlled vocabulary.

See the related document outlining the suggestions for the 1.4 Chado release: https://docs.google.com/document/d/1t_Jb4XxUPtgGRSKtznsqvjTjmR4vpFHPQROMQ0OZK9A/edit?usp=sharing

- [x] cell_line
- [x] companalysis
- [x] contact
- [x] cv

- [x] db

- [x] expression

- [x] general

- [x] genetic

- [x] interaction

- [x] library

- [x] mage

- [x] map

- [x] natural_diversity

- [x] organism

- [x] phenotype

- [x] phylogeny

- [x] project

- [x] pub

- [x] sequence

- [x] stock

- [x] www

**Comment by spficklin** [comment]
Let's consider adding this to all prop tables for consistency.

**Comment by scottcain** [comment]
Adding this Chado-wide is a good idea, but is also a fairly wide-ranging suggested change (and would take a while to implement, if only because there are so many tables that would be effected).  I'm not saying don't do this (in fact I'll reiterate that it's a really good idea), just that it will take a while :-)

**Comment by spficklin** [comment]
Suggested code...

Add these lines to the prop table.
```
cvalue_id bigint,
FOREIGN KEY (cvalue_id) REFERENCES cvterm (cvterm_id) ON DELETE SET NULL,
```
Add this comment for each prop table:
COMMENT ON COLUMN {table}.cvalue_id IS 'The value of the property if that value should be the name of a controlled vocabulary term.  It is preferred that a property either use the value or cvalue_id column but not both.  For example, if the property type is "color" then the cvalue_id could be a term named "green".';

**Comment by bradfordcondon** [comment]
We are going to skip cvtermprop tables (ie `cell_line_cvtermprop`).  It sounds like this table accomplishes something similar to what we're doing with teh `cvalue` column but maybe not exactly the same.

We will still be adding `cvalue` to the prop tables for modules that have a cvtermprop table.

IE for `cell_line` we add `cell_lineprop` but ignore `cell_line_cvtermprop`

**Comment by laceysanderson** [comment]
Very excited about this change :-D

**Comment by bradfordcondon** [comment]
PR merged, closing.
