### ISSUE TITLE
“Variable” table (v1.4)

### ISSUE THREAD

**Issue by spficklin** [GMOD/Chado#45]
This issue imported from the [Chado v1.4 requested changes](https://docs.google.com/document/d/1t_Jb4XxUPtgGRSKtznsqvjTjmR4vpFHPQROMQ0OZK9A/edit) google doc:

For those using Drupal/Tripal, I’d like the same kind of table for variables that would be used to store some global informations like the Chado schema version, or the installed plugins, or some custom comments or whatever. The table would have 2 text columns: name and value.
I’d like to see in that table a first variable being ‘chado_schema_version’ = ‘1.4’ and I would like to use it to store the Chado Controller version installed on the database if one, like ‘chaco_version’=’2.0’ for instance. It would be useful for future updates or compatibility check with other Chado modules. I would also like to use that table to store some parameters like ‘chaco_authentication_mode’ = ‘postgresql’ or ‘tripal’ or… You see what I mean? This table could/should be used by Chado modules in order to store some informations that could not be stored anywhere else in the database.

- Stephen says (4/24/2015): Because variables would be application specific I think this type of table should be created by the application (i.e. Tripal). in fact we’ve had some discussions about creating such a table for Tripal.

**Comment by spficklin** [comment]
Sample code from the Google Doc
```
CREATE TABLE variable (
  name TEXT NULL DEFAULT NULL,
  value TEXT NULL DEFAULT NULL,
  UNIQUE(name)
);
COMMENT ON TABLE variable IS 'Use this table to store Chado module parameters that can not be stored anywhere else such as installed module version.';
INSERT INTO variable VALUES ('chado_schema_version', '1.4');

```

**Comment by bradfordcondon** [comment]
It sounds like we don't want to implement this in Chado.  I propose we close this issue.

**Comment by scottcain** [comment]
I'm inclined to agree. I'm guessing this request came from @guignonv .  Care to comment Valentin?

**Comment by spficklin** [comment]
Tagging Valentin for a comment... @guignonv

**Comment by guignonv** [comment]
Sorry, I missed that request here! But after a couple of month, I can comment! :-p
Well, it can be on the application side but I don't see an easy way to check which version of Chado is installed. What I see, on my application side, to guess the Chado version installed is to check is some specific tables or columns exist. It can be achieve this way but I think it's prone to errors.
On the other hand, we already had many releases of Chado without any straight way to get the version installed so anyway, solving that problem "now" would be too late anyway...

**Comment by ekcannon** [comment]
It looks like the version is implemented. There is a table named chadoprop, which in the peanutbase instance, contains one record of type "version", indicating the version is 1.3 (though I think it should be 1.31). I don't know where this record is being set.

**Comment by scottcain** [comment]
Yay, one I can close.  

PS, I think it's 1.3, since that is the schema version.  Scripts and whatnot changed between 1.3 and 1.31 but the schema did not (if I'm recalling correctly).
