### ISSUE TITLE
Core Goal: using modern schema deployment

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#64]
I was discussing with my group ways to make Chado easier to maintain.  I need to preface this by saying I only watched Stephen write the diffs himself, I haven't done it so my understanding is limited.  But.  It seems like right now when you make changes to Chado, you have to change the SQL for installing that verison from scratch, and then also create diff files to go from any previous version of chado. 
It seems like a lot of work.

The [laravel](https://laravel.com/) php framework uses database migrations for this sort of thing.  Changes to the DB structure are made sequentially, so all you need to do to upgrade is run migrations your site hasn't run yet. Instead of two types of files, one of which seems to be a fair amount of work to do, you only have one: the migration file.  Each change to the db is a single migration file.  You can see our use of migrations for our [TreeSnap site here](https://github.com/statonlab/Treesnap-website/tree/master/database/migrations).  For exmaple, [this migration adds a single table to the db](https://github.com/statonlab/Treesnap-website/blob/master/database/migrations/2018_04_11_144606_create_events_table.php).  A future migration might modify a column.

The main disadvantage of migrations is we introduce a dependency.  We clearly wouldn't use laravel, since its an arbitrary php framework.  But why not a package manager like pip, gems, or composer?  Chado would remain platform agnostic, you would introduce a dependency but its likely is already in use on the server.
And, the main benefit: it becomes *much* easier to contribute to, and maintain, Chado.

**Comment by isumoc** [comment]
Hi @bradfordcondon,

Have you looked at any schema migration tools such as https://github.com/flyway/flyway ? These tools would allow Chado to avoid Dependency Hell™  but still offer some users the convenience of managed migrations.

Also, Drupal 8 has a "migrate API". I would assume that Tripal 4/Drupal 8 will be able to implement migrations using this for Tripal users ?

**Comment by bradfordcondon** [comment]
A discussion brought this issue back into my sites.  I think flyway is a totally reasonable suggestion.  In addition to [flyaway](https://github.com/flyway/flyway) we can consider:

* http://www.liquibase.org/
* https://github.com/cbbrowne/mahout
* https://github.com/sqitchers/sqitch
* https://github.com/mbryzek/schema-evolution-manager
* https://github.com/mfine/postgresql-schema
* https://github.com/djrobstep/migra

**Comment by scottcain** [comment]
I would be TOTALLY in favor of this!

**Comment by bradfordcondon** [comment]
I spent some time working on this.  I think flyway is my choice.  Its very simple, its very well supported, and installation/setup is easy.


Basically once you install flyway, you would have this Chado project repository somewhere in your file system, and you would point your flyway configuration to it.

Chado would then have "migration" scripts.  Each migration script is a simple SQL file (add a table, drop a column, whatever).  As Chado is developed, minor versions get released that add new migration scripts: we can still release major versions as we see fit.  The naming of the migration corresponds to hte version.  [see this for detailed explanation of how versioning is handled in the script name](https://auth0.com/blog/incrementally-changing-your-database-with-java-and-flyway/)


  When a site wants to update its Chado version, it simply downloads the latest Chado release and runs `flyway migrate`.  Flyway then runs the migration SQL scripts in order, from where the database is currently sitting at.

To try it out, i created a single migration script that adds a new table.  Running `flyway info` shows me that i have one pending migration:
```
flyway info
+-----------+---------+-----------------------+----------+---------------------+----------+
| Category  | Version | Description           | Type     | Installed On        | State    |
+-----------+---------+-----------------------+----------+---------------------+----------+
|           | 1       | << Flyway Baseline >> | BASELINE | 2018-12-20 14:31:32 | Baseline |
| Versioned | 1.1     | try1                  | SQL      |                     | Pending  |
+-----------+---------+-----------------------+----------+---------------------+----------+
```

After running `flyway migrate` -

```
 flyway info
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:postgresql://localhost:5432/drupal (PostgreSQL 10.5)
Schema version: 1.1

+-----------+---------+-----------------------+----------+---------------------+----------+
| Category  | Version | Description           | Type     | Installed On        | State    |
+-----------+---------+-----------------------+----------+---------------------+----------+
|           | 1       | << Flyway Baseline >> | BASELINE | 2018-12-20 14:27:35 | Baseline |
| Versioned | 1.1     | try1                  | SQL      | 2018-12-20 14:43:11 | Success  |
+-----------+---------+-----------------------+----------+---------------------+----------+

```

teh SQL script ran and I now have the modifications performed in the migration script (see state = success).

The great thing is each site is free to migrate as frequently or infrequently as they want.  You no longer have to provide diff files between versions: simply running migrate will get databases up to speed.

**Comment by bradfordcondon** [comment]
this is implemented.  If you need help learning how to use it, see #94
