### ISSUE TITLE
Migration 1.3.3.001 fails on PostgreSQL 9.4

### ISSUE THREAD

**Issue by laceysanderson** [GMOD/Chado#96]
The first migration fails on PostgreSQL 9.4
```
$ flyway migrate
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:postgresql://localhost:5432/tripal_dev (PostgreSQL 9.4)
Current version of schema "chado": 1
Migrating schema "chado" to version 1.3.3.001 - add stock biomat table
ERROR: Migration of schema "chado" to version 1.3.3.001 - add stock biomat table failed! Changes successfully rolled back.
ERROR: 
Migration V1.3.3.001__add_stock_biomat_table.sql failed
-------------------------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near "NOT"
  Position: 17
Location   : /home/www/Chado/chado/migrations/V1.3.3.001__add_stock_biomat_table.sql (/home/www/Chado/chado/migrations/V1.3.3.001__add_stock_biomat_table.sql)
Line       : 10
Statement  : CREATE INDEX IF NOT EXISTS biomaterial_project_idx1 ON biomaterial_project USING btree (biomaterial_id)
```

The failure was due to `IF NOT EXISTS` which is 9.5 specific (See [9.4](https://www.postgresql.org/docs/9.4/sql-createindex.html) vs. [9.5](https://www.postgresql.org/docs/9.5/sql-createindex.html)).

**Comment by bradfordcondon** [comment]
oh no!  Thanks!
Let's set up a matrix build on Travis so this doesnt happen again.

**Comment by bradfordcondon** [comment]
I set up a [matrix build branch](https://github.com/GMOD/Chado/tree/matrix), we can see that 9.2 &4 fail but 9.6 passes.

* what postgres versions should explicitly be tested in the build?  what does Chado support?
* I really liked the `CREATE INDEX IF NOT EXIST`.  is there some way to support this behavior while supporting 9.4?  If not we will just have to blindly create and users who already have the index will have to pass the flyway option to ignore that migration...

**Comment by bradfordcondon** [comment]
We have a matrix build on multiple postgres versions to ensure this wont happen in the future, and that migration has been fixed. closing.  thank you Lacey for bringing it to our attention.
